name: libft_test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash

        steps:
          - uses: actions/checkout@v4
            with:
              submodules: recursive
          - name: make
            run: |
                sudo apt-get update && sudo apt-get install make git clang valgrind -y
                sed -i 's/-I$(LIBFT_PATH)/-I$(LIBFT_PATH)\/include/g' libftTester/Makefile
                sed -i 's/tput setaf [0-9]* &&//g' libftTester/Makefile
                sed -i 's/tput setaf [0-9]*//g' libftTester/Makefile
                make a -C libftTester
